### ISSUE TITLE
Installation has failed with exit code 101 - missing ftdi

### ISSUE THREAD

**Issue by kzajac83** [espressif/idf-installer#269]
Hello

The same problem as #100 

![image](https://github.com/user-attachments/assets/201bb6e0-4bc8-427e-96aa-26d650c67213)

Chossing all option like zip archives or githubs repositoers nothing change.

![image](https://github.com/user-attachments/assets/9c05dcee-de3b-40f0-b4f1-3349cd5def2a)

Genere missing files mentioned in error log but I try  install as admin but not help too. 

Help only  exclude ftdi drivers from installer. 

My OS in Windows 10 Home

PS. On all Windows channel button now work after appear error, eg clicking cancel here nothing happened:

![image](https://github.com/user-attachments/assets/5fbe0b1b-a438-41f9-9798-5a82fb3afbb3)

**Comment by kzajac83** [comment]
@kehkou Why need download  something from mediafire.com, some mailware probabky this is

**Comment by kzajac83** [comment]
PS. On installing occure error on end, not sure finally installed or not?? 

![image](https://github.com/user-attachments/assets/8bb62eb5-6571-4a9d-9758-8e0f5171f2df)

[Setup Log 2024-08-29 #004.txt](https://github.com/user-attachments/files/16795656/Setup.Log.2024-08-29.004.txt)

**Comment by jakub-kocka** [comment]
Hello @kzajac83, we are sorry for the inconvenience there has been some issue with the builds of the Installer because of the FTDI driver.

Right now all the builds should be fixed again and available on the Installer's page https://dl.espressif.com/dl/esp-idf/

Thank you for your understanding.

**Comment by kzajac83** [comment]
Thank you @jakub-kocka for driver issue fix however 2nd issue still exist:

![image](https://github.com/user-attachments/assets/aeb3eee5-948f-4b66-84fb-46df34840aff)

[Setup Log 2024-08-30 #002.txt](https://github.com/user-attachments/files/16812917/Setup.Log.2024-08-30.002.txt)

**Comment by jakub-kocka** [comment]
@kzajac83 Can you try to install the IDF into the `C` drive?
This error looks a bit strange and this might help to move.

**Comment by kzajac83** [comment]
Installing 1st time [esp-idf-tools-setup-online-2.28.exe](https://dl.espressif.com/dl/idf-installer/esp-idf-tools-setup-online-2.28.exe?) (Universal Installer) appear request to add something to MS registry and I do that, next appear issue with drivers plus 2nd mentioned issue.  Next time using Universal Installer no request for add key to the registry and after add missing drivers stay only 2nd issue. Before every next attempt installation deleting D:\Espressif directory.

Next I decide to download ~2GB offline installer [esp-idf-tools-setup-espressif-ide-3.0.0-with-esp-idf-5.2.2.exe](https://dl.espressif.com/dl/idf-installer/esp-idf-tools-setup-espressif-ide-3.0.0-with-esp-idf-5.2.2.exe?) and on begging of installation appear request to add below to registry:

`powershell -Command "&{ Start-Process -FilePath reg 'ADD HKLM\SYSTEM\CurrentControlSet\Control\FileSystem /v LongPathsEnabled /t REG_DWORD /d 1 /f' -Verb runAs}"
`

I don't know this is the same as Universal Installer request one time but, if yest then I add it already and Universal Installer not requested any more for that.  But Offline Installer request the same (or this is other registry requesty add ??).

Anyway after use Offline Installer and use drive D:\ all pass fine. 

Something wrong must be in Universal Installer, maybe something is not downloading? 

Anyway probably I will not more need installing hence cannot help more but if something need please ask. 

BR, Krzysiek

**Comment by jakub-kocka** [comment]
Thank you for the information, we will take a look and check if everything is correct.

I am glad that it works for you.

**Comment by jappies** [comment]
Seems that the FTDI driver download is not working

![afbeelding](https://github.com/user-attachments/assets/8d6f503e-925f-4681-b0e4-a05e976cf553)

**Comment by georgik** [comment]
@hahihula Would it be possible to use newly developed Insaller to resolve the problem?
